INFO_TABLE = 'wr_info'

TYPE = 'wr_type'
CHASSIS = 'chassis'
LEG_COMPONENT = 'leg'

CHASSIS_SIDE_NUMBERS = {}
CHASSIS_LEFT_ARM = 1
CHASSIS_RIGHT_ARM = 2
CHASSIS_LEFT_LEG= 3
CHASSIS_RIGHT_LEG = 4
CHASSIS_BODY = 5
CHASSIS_HEAD = 6
CHASSIS_SIDE_NUMBERS[CHASSIS_LEFT_ARM] = 'wr_chassis_side_1'
CHASSIS_SIDE_NUMBERS[CHASSIS_RIGHT_ARM] = 'wr_chassis_side_2'
CHASSIS_SIDE_NUMBERS[CHASSIS_LEFT_LEG] = 'wr_chassis_side_3'
CHASSIS_SIDE_NUMBERS[CHASSIS_RIGHT_LEG] = 'wr_chassis_side_4'
CHASSIS_SIDE_NUMBERS[CHASSIS_BODY] = 'wr_chassis_side_5'
CHASSIS_SIDE_NUMBERS[CHASSIS_HEAD] = 'wr_chassis_side_6'

CHASSIS_1_CONSTRUCTION_P = 'wr_chassis_1_p'
CHASSIS_1_CONSTRUCTION_R = 'wr_chassis_1_r'

CHASSIS_CONSTRUCTION_OFFSETS = 'wr_chassis_offsets'
CCO_LEFT_ARM_X = 'left_arm_x'
CCO_RIGHT_ARM_X = 'right_arm_x'
CCO_BODY_Z = 'body_z'
CCO_HEAD_Y = 'head_y'
CCO_LEG_Y = 'leg_y'
CCO_LEFT_LEG_X = 'left_leg_x'
CCO_RIGHT_LEG_X = 'right_leg_x'

